### ISSUE TITLE
villages seem to be infected way too fast after 1.5.0

### ISSUE THREAD

**Issue by lag42** [jedijoe93/ImmortuosCalyx#4]
in version 1.4.2 of the mod i could walk into a newly generated village with minimal problems, post-1.5.0 something seems to have gone wrong and going within the bounds of any village will consistently result in an infection

i think the infection became contagious at all levels rather than at 50% with the rewrites now

tested with a clean instance of only:
minecraft 1.16.5
forge 36.2.8
immortuos calyx 1.4.2 & 1.5.1 respectively

**Comment by CartoonishVillain** [comment]
May be an error with the rewrite of how infections are handled that started in 1.5. Looking into it.

**Comment by CartoonishVillain** [comment]
This is quite embarrassing.

I found out why this is occuring. I rewrote almost every infection method as the code was originally quite messy.

This is a part of a system called "Aerosol" infections. Basically an infected entity coughs on you to infect. These run random number generators with usually really low odds to actually give infections. What happened here was I forgot to actually lock all the infection stuff... behind those random number generators. So any time you get within range of say, a villager that's a follower of the disease, you'd immediately get infected.

This will be fixed in 1.5.1.1 which should launch within the hour barring any major issues. 

Thank you for reporting this issue!
